"""initial schema

Revision ID: 26a4acfe5afa
Revises: 
Create Date: 2026-03-17 17:11:24.976184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26a4acfe5afa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=500), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('requested_role', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_requests_username'), 'access_requests', ['username'], unique=False)
    op.create_table('analysis_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cdm_name', sa.String(length=255), nullable=False),
    sa.Column('omop_schema', sa.String(length=255), nullable=True),
    sa.Column('top_unmapped_terms', sa.Integer(), nullable=True),
    sa.Column('top_concepts', sa.Integer(), nullable=True),
    sa.Column('max_records_per_person', sa.Integer(), nullable=True),
    sa.Column('max_observation_months', sa.Integer(), nullable=True),
    sa.Column('comparison_alert_threshold', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_settings_cdm_name'), 'analysis_settings', ['cdm_name'], unique=True)
    op.create_table('analysis_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cdm_name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cdm_name', 'domain', 'version', name='uq_snapshot_cdm_domain_version')
    )
    op.create_index(op.f('ix_analysis_snapshots_cdm_name'), 'analysis_snapshots', ['cdm_name'], unique=False)
    op.create_index(op.f('ix_analysis_snapshots_domain'), 'analysis_snapshots', ['domain'], unique=False)
    op.create_index('ix_snapshots_cdm_domain', 'analysis_snapshots', ['cdm_name', 'domain'], unique=False)
    op.create_index('ix_snapshots_cdm_domain_version', 'analysis_snapshots', ['cdm_name', 'domain', 'version'], unique=False)
    op.create_table('cdm_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cdm_name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('granted_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cdm_name', 'username', name='uq_cdm_access')
    )
    op.create_index(op.f('ix_cdm_access_cdm_name'), 'cdm_access', ['cdm_name'], unique=False)
    op.create_index(op.f('ix_cdm_access_username'), 'cdm_access', ['username'], unique=False)
    op.create_table('cdm_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('db_host', sa.String(length=255), nullable=False),
    sa.Column('db_port', sa.Integer(), nullable=False),
    sa.Column('db_name', sa.String(length=255), nullable=False),
    sa.Column('db_user', sa.String(length=255), nullable=False),
    sa.Column('db_password_encrypted', sa.Text(), nullable=False),
    sa.Column('omop_schema', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cdm_configs_name'), 'cdm_configs', ['name'], unique=True)
    op.create_table('cdm_group_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cdm_name', sa.String(length=255), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('granted_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cdm_name', 'group_name', name='uq_cdm_group_access')
    )
    op.create_index(op.f('ix_cdm_group_access_cdm_name'), 'cdm_group_access', ['cdm_name'], unique=False)
    op.create_index(op.f('ix_cdm_group_access_group_name'), 'cdm_group_access', ['group_name'], unique=False)
    op.create_table('cohort_shares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('share_type', sa.String(length=20), nullable=False),
    sa.Column('share_target', sa.String(length=255), nullable=False),
    sa.Column('shared_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cohort_id', 'share_type', 'share_target', name='uq_cohort_share')
    )
    op.create_index(op.f('ix_cohort_shares_cohort_id'), 'cohort_shares', ['cohort_id'], unique=False)
    op.create_table('cohort_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('criteria_json', sa.JSON(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cohort_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('criteria_json', sa.JSON(), nullable=False),
    sa.Column('generated_sql', sa.Text(), nullable=True),
    sa.Column('patient_count', sa.Integer(), nullable=True),
    sa.Column('characterization_json', sa.JSON(), nullable=True),
    sa.Column('characterized_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cohort_id', 'version', name='uq_cohort_version')
    )
    op.create_index(op.f('ix_cohort_versions_cohort_id'), 'cohort_versions', ['cohort_id'], unique=False)
    op.create_index('ix_cohort_versions_cohort_version', 'cohort_versions', ['cohort_id', 'version'], unique=False)
    op.create_table('cohorts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cdm_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('shared_with_all', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohorts_cdm_name'), 'cohorts', ['cdm_name'], unique=False)
    op.create_index(op.f('ix_cohorts_created_by'), 'cohorts', ['created_by'], unique=False)
    op.create_table('concept_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('cdm_name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('concepts_json', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_sets_cdm_name'), 'concept_sets', ['cdm_name'], unique=False)
    op.create_table('estimation_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cdm_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('target_cohort_id', sa.Integer(), nullable=False),
    sa.Column('outcome_cohort_id', sa.Integer(), nullable=False),
    sa.Column('parameters_json', sa.Text(), nullable=True),
    sa.Column('results_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estimation_analyses_cdm_name'), 'estimation_analyses', ['cdm_name'], unique=False)
    op.create_table('incidence_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cdm_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('target_cohort_id', sa.Integer(), nullable=False),
    sa.Column('outcome_cohort_id', sa.Integer(), nullable=False),
    sa.Column('parameters_json', sa.Text(), nullable=True),
    sa.Column('results_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidence_analyses_cdm_name'), 'incidence_analyses', ['cdm_name'], unique=False)
    op.create_table('mapping_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cdm_name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('source_value', sa.String(length=1000), nullable=False),
    sa.Column('source_name', sa.String(length=1000), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_concept_id', sa.Integer(), nullable=True),
    sa.Column('target_concept_name', sa.String(length=500), nullable=True),
    sa.Column('target_vocabulary_id', sa.String(length=100), nullable=True),
    sa.Column('previous_concept_id', sa.Integer(), nullable=True),
    sa.Column('suggestion_source', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('user', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mapping_decisions_cdm_domain', 'mapping_decisions', ['cdm_name', 'domain'], unique=False)
    op.create_index('ix_mapping_decisions_cdm_domain_sv', 'mapping_decisions', ['cdm_name', 'domain', 'source_value'], unique=False)
    op.create_index(op.f('ix_mapping_decisions_cdm_name'), 'mapping_decisions', ['cdm_name'], unique=False)
    op.create_index(op.f('ix_mapping_decisions_domain'), 'mapping_decisions', ['domain'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('notif_type', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'notif_type', name='uq_notif_pref')
    )
    op.create_index(op.f('ix_notification_preferences_username'), 'notification_preferences', ['username'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('item_id', sa.String(length=500), nullable=True),
    sa.Column('read', sa.Integer(), nullable=True),
    sa.Column('target_role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_item_id'), 'notifications', ['item_id'], unique=False)
    op.create_index(op.f('ix_notifications_target_role'), 'notifications', ['target_role'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['username', 'read'], unique=False)
    op.create_index(op.f('ix_notifications_username'), 'notifications', ['username'], unique=False)
    op.create_table('reference_codebooks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'code', name='uq_ref_name_code')
    )
    op.create_index(op.f('ix_reference_codebooks_code'), 'reference_codebooks', ['code'], unique=False)
    op.create_index(op.f('ix_reference_codebooks_domain'), 'reference_codebooks', ['domain'], unique=False)
    op.create_index(op.f('ix_reference_codebooks_name'), 'reference_codebooks', ['name'], unique=False)
    op.create_table('sapbert_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('source_code', sa.String(length=255), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('target_concept_id', sa.Integer(), nullable=False),
    sa.Column('target_concept_code', sa.String(length=255), nullable=True),
    sa.Column('target_concept_name', sa.String(length=500), nullable=True),
    sa.Column('target_vocabulary_id', sa.String(length=100), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sapbert_mappings_domain'), 'sapbert_mappings', ['domain'], unique=False)
    op.create_index(op.f('ix_sapbert_mappings_source_code'), 'sapbert_mappings', ['source_code'], unique=False)
    op.create_table('saved_queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cdm_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('sql', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_queries_cdm_name'), 'saved_queries', ['cdm_name'], unique=False)
    op.create_table('user_favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.String(length=500), nullable=False),
    sa.Column('item_label', sa.String(length=500), nullable=True),
    sa.Column('item_meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'item_type', 'item_id', name='uq_user_fav')
    )
    op.create_index(op.f('ix_user_favorites_username'), 'user_favorites', ['username'], unique=False)
    op.create_table('user_group_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('added_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_name', 'username', name='uq_group_member')
    )
    op.create_index(op.f('ix_user_group_members_group_name'), 'user_group_members', ['group_name'], unique=False)
    op.create_index(op.f('ix_user_group_members_username'), 'user_group_members', ['username'], unique=False)
    op.create_table('user_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_groups_name'), 'user_groups', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_groups_name'), table_name='user_groups')
    op.drop_table('user_groups')
    op.drop_index(op.f('ix_user_group_members_username'), table_name='user_group_members')
    op.drop_index(op.f('ix_user_group_members_group_name'), table_name='user_group_members')
    op.drop_table('user_group_members')
    op.drop_index(op.f('ix_user_favorites_username'), table_name='user_favorites')
    op.drop_table('user_favorites')
    op.drop_index(op.f('ix_saved_queries_cdm_name'), table_name='saved_queries')
    op.drop_table('saved_queries')
    op.drop_index(op.f('ix_sapbert_mappings_source_code'), table_name='sapbert_mappings')
    op.drop_index(op.f('ix_sapbert_mappings_domain'), table_name='sapbert_mappings')
    op.drop_table('sapbert_mappings')
    op.drop_index(op.f('ix_reference_codebooks_name'), table_name='reference_codebooks')
    op.drop_index(op.f('ix_reference_codebooks_domain'), table_name='reference_codebooks')
    op.drop_index(op.f('ix_reference_codebooks_code'), table_name='reference_codebooks')
    op.drop_table('reference_codebooks')
    op.drop_index(op.f('ix_notifications_username'), table_name='notifications')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_target_role'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_item_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_preferences_username'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_mapping_decisions_domain'), table_name='mapping_decisions')
    op.drop_index(op.f('ix_mapping_decisions_cdm_name'), table_name='mapping_decisions')
    op.drop_index('ix_mapping_decisions_cdm_domain_sv', table_name='mapping_decisions')
    op.drop_index('ix_mapping_decisions_cdm_domain', table_name='mapping_decisions')
    op.drop_table('mapping_decisions')
    op.drop_index(op.f('ix_incidence_analyses_cdm_name'), table_name='incidence_analyses')
    op.drop_table('incidence_analyses')
    op.drop_index(op.f('ix_estimation_analyses_cdm_name'), table_name='estimation_analyses')
    op.drop_table('estimation_analyses')
    op.drop_index(op.f('ix_concept_sets_cdm_name'), table_name='concept_sets')
    op.drop_table('concept_sets')
    op.drop_index(op.f('ix_cohorts_created_by'), table_name='cohorts')
    op.drop_index(op.f('ix_cohorts_cdm_name'), table_name='cohorts')
    op.drop_table('cohorts')
    op.drop_index('ix_cohort_versions_cohort_version', table_name='cohort_versions')
    op.drop_index(op.f('ix_cohort_versions_cohort_id'), table_name='cohort_versions')
    op.drop_table('cohort_versions')
    op.drop_table('cohort_templates')
    op.drop_index(op.f('ix_cohort_shares_cohort_id'), table_name='cohort_shares')
    op.drop_table('cohort_shares')
    op.drop_index(op.f('ix_cdm_group_access_group_name'), table_name='cdm_group_access')
    op.drop_index(op.f('ix_cdm_group_access_cdm_name'), table_name='cdm_group_access')
    op.drop_table('cdm_group_access')
    op.drop_index(op.f('ix_cdm_configs_name'), table_name='cdm_configs')
    op.drop_table('cdm_configs')
    op.drop_index(op.f('ix_cdm_access_username'), table_name='cdm_access')
    op.drop_index(op.f('ix_cdm_access_cdm_name'), table_name='cdm_access')
    op.drop_table('cdm_access')
    op.drop_index('ix_snapshots_cdm_domain_version', table_name='analysis_snapshots')
    op.drop_index('ix_snapshots_cdm_domain', table_name='analysis_snapshots')
    op.drop_index(op.f('ix_analysis_snapshots_domain'), table_name='analysis_snapshots')
    op.drop_index(op.f('ix_analysis_snapshots_cdm_name'), table_name='analysis_snapshots')
    op.drop_table('analysis_snapshots')
    op.drop_index(op.f('ix_analysis_settings_cdm_name'), table_name='analysis_settings')
    op.drop_table('analysis_settings')
    op.drop_index(op.f('ix_access_requests_username'), table_name='access_requests')
    op.drop_table('access_requests')
    # ### end Alembic commands ###
